import { bemaraColorRoles, bemaraColors, bemaraMotion, bemaraRadii, bemaraSpacing } from ".";

export const bemaraCssVariables = {
  "--bemara-color-black-plum": bemaraColors.blackPlum,
  "--bemara-color-bordeaux-noir": bemaraColors.bordeauxNoir,
  "--bemara-color-mauve-taupe": bemaraColors.mauveTaupe,
  "--bemara-color-rose-beige": bemaraColors.roseBeige,
  "--bemara-color-silk-cream": bemaraColors.silkCream,
  "--bemara-color-ivory": bemaraColors.ivory,
  "--bemara-canvas": bemaraColorRoles.canvas,
  "--bemara-canvas-warm": bemaraColorRoles.canvasWarm,
  "--bemara-ink": bemaraColorRoles.ink,
  "--bemara-ink-soft": bemaraColorRoles.inkSoft,
  "--bemara-brand": bemaraColorRoles.brand,
  "--bemara-surface-warm": bemaraColorRoles.surfaceWarm,
  "--bemara-border-subtle": bemaraColorRoles.borderSubtle,
  "--bemara-focus-ring": bemaraColorRoles.focusRing,
  "--bemara-radius-control": bemaraRadii.control,
  "--bemara-radius-card": bemaraRadii.card,
  "--bemara-radius-editorial-panel": bemaraRadii.editorialPanel,
  "--bemara-space-1": bemaraSpacing[1],
  "--bemara-space-2": bemaraSpacing[2],
  "--bemara-space-3": bemaraSpacing[3],
  "--bemara-space-4": bemaraSpacing[4],
  "--bemara-space-5": bemaraSpacing[5],
  "--bemara-space-6": bemaraSpacing[6],
  "--bemara-space-8": bemaraSpacing[8],
  "--bemara-space-10": bemaraSpacing[10],
  "--bemara-space-12": bemaraSpacing[12],
  "--bemara-space-16": bemaraSpacing[16],
  "--bemara-space-20": bemaraSpacing[20],
  "--bemara-motion-quick": bemaraMotion.quick,
  "--bemara-motion-standard": bemaraMotion.standard,
  "--bemara-motion-expressive": bemaraMotion.expressive,
  "--bemara-motion-easing": bemaraMotion.easing,
} as const;
